# Generated by Django 5.2.16 on 2026-08-16 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messagerie', '0002_alter_conversation_options_alter_message_options_and_more'),
        ('produits', '0005_favori'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='produit_contexte',
            field=models.ForeignKey(blank=True, help_text="Dernier produit à l'origine du contact — affiché en haut du chat.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations_associees', to='produits.produit'),
        ),
        migrations.AddField(
            model_name='message',
            name='produit',
            field=models.ForeignKey(blank=True, help_text="Produit concerné si ce message provient d'un clic 'Contacter le vendeur'.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='produits.produit'),
        ),
    ]
