# Generated by Django 5.2.16 on 2026-07-16 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facture',
            options={'verbose_name': 'Facture', 'verbose_name_plural': 'Factures'},
        ),
    ]
