# Generated by Django 6.0.7 on 2026-07-15 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Catégorie',
            },
        ),
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.FloatField()),
                ('date', models.DateField()),
                ('type', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('commercant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depenses', to='users.commercant')),
            ],
            options={
                'verbose_name': 'Dépense',
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('prix_achat', models.FloatField()),
                ('prix_vente', models.FloatField()),
                ('frais_packaging', models.FloatField(default=0)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('archive', 'Archivé')], default='actif', max_length=10)),
                ('quantite', models.IntegerField(default=0)),
                ('seuil_alerte', models.IntegerField(default=5)),
                ('seuil_dormant', models.IntegerField(default=60)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('categorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produits', to='produits.categorie')),
                ('commercant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='users.commercant')),
            ],
            options={
                'verbose_name': 'Produit',
            },
        ),
        migrations.CreateModel(
            name='OffreProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=150)),
                ('taux', models.FloatField(help_text='Taux de réduction en %')),
                ('description', models.TextField(blank=True)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('produit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='offre', to='produits.produit')),
            ],
            options={
                'verbose_name': 'Offre Produit',
            },
        ),
        migrations.CreateModel(
            name='ImageProd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.ImageField(upload_to='produits/')),
                ('nom', models.CharField(blank=True, max_length=100)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='produits.produit')),
            ],
            options={
                'verbose_name': 'Image Produit',
            },
        ),
    ]
