# Generated by Django 5.2.16 on 2026-07-16 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorie',
            options={'verbose_name': 'Catégorie', 'verbose_name_plural': 'Catégories'},
        ),
        migrations.AlterModelOptions(
            name='depense',
            options={'ordering': ['-date'], 'verbose_name': 'Dépense', 'verbose_name_plural': 'Dépenses'},
        ),
        migrations.AlterModelOptions(
            name='imageprod',
            options={'verbose_name': 'Image Produit', 'verbose_name_plural': 'Images Produits'},
        ),
        migrations.AlterModelOptions(
            name='offreproduit',
            options={'verbose_name': 'Offre Produit', 'verbose_name_plural': 'Offres Produits'},
        ),
        migrations.AlterModelOptions(
            name='produit',
            options={'ordering': ['-date_creation'], 'verbose_name': 'Produit', 'verbose_name_plural': 'Produits'},
        ),
        migrations.RenameField(
            model_name='imageprod',
            old_name='url',
            new_name='image',
        ),
        migrations.AddField(
            model_name='imageprod',
            name='est_principale',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='produit',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produits', to='produits.categorie'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='seuil_alerte',
            field=models.IntegerField(default=5, help_text='Alerte quand le stock descend sous ce seuil'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='seuil_dormant',
            field=models.IntegerField(default=60, help_text='Nb de jours sans vente avant alerte stock dormant'),
        ),
    ]
