# Generated by Django 5.2.16 on 2026-07-26 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0002_alter_categorie_options_alter_depense_options_and_more'),
        ('users', '0002_alter_administrateur_options_alter_client_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Approvisionnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField(help_text='Quantité reçue du fournisseur')),
                ('prix_achat_unitaire', models.FloatField(help_text="Prix d'achat unitaire lors de cet approvisionnement")),
                ('fournisseur', models.CharField(blank=True, help_text='Nom du fournisseur (optionnel)', max_length=200)),
                ('note', models.TextField(blank=True, help_text='Remarques sur cet approvisionnement')),
                ('date_approvisionnement', models.DateField(auto_now_add=True)),
                ('commercant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvisionnements', to='users.commercant')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvisionnements', to='produits.produit')),
            ],
            options={
                'verbose_name': 'Approvisionnement',
                'verbose_name_plural': 'Approvisionnements',
                'ordering': ['-date_approvisionnement'],
            },
        ),
    ]
