# Generated by Django 5.2.16 on 2026-07-28 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0003_approvisionnement'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='attribut',
            field=models.CharField(blank=True, help_text='Ex: Taille, Couleur, Matière...', max_length=255),
        ),
        migrations.AlterField(
            model_name='produit',
            name='seuil_alerte',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='produit',
            name='seuil_dormant',
            field=models.IntegerField(default=60),
        ),
    ]
