# Generated by Django 6.1 on 2026-08-10 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0004_produit_attribut_alter_produit_seuil_alerte_and_more'),
        ('users', '0002_alter_administrateur_options_alter_client_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoris', to='users.client')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorise_par', to='produits.produit')),
            ],
            options={
                'verbose_name': 'Favori',
                'verbose_name_plural': 'Favoris',
                'ordering': ['-date_ajout'],
                'unique_together': {('client', 'produit')},
            },
        ),
    ]
