# Generated by Django 5.2.16 on 2026-09-12 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0006_delete_offreproduit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='statut',
            field=models.CharField(choices=[('actif', 'Actif'), ('archive', 'Archivé'), ('supprime', 'Supprimé')], default='actif', max_length=10),
        ),
    ]
