# Generated by Django 6.1.1 on 2026-09-18 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0007_alter_produit_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='couleurs_disponibles',
            field=models.CharField(blank=True, help_text='Ex: Marron, Bleu, Rose (séparées par des virgules)', max_length=255),
        ),
        migrations.AddField(
            model_name='produit',
            name='tailles_disponibles',
            field=models.CharField(blank=True, help_text="Ex: S,M,L (laisser vide si l'article n'a pas de taille)", max_length=100),
        ),
        migrations.AlterField(
            model_name='produit',
            name='attribut',
            field=models.CharField(blank=True, help_text='Ex: Matière, marque, particularité...', max_length=255),
        ),
    ]
