# Generated by Django 6.1.1 on 2026-09-17 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0007_alter_produit_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='couleur',
            field=models.CharField(blank=True, help_text='Ex: Marron, Bleu, Rose... (laisser vide si non applicable)', max_length=50),
        ),
        migrations.AddField(
            model_name='produit',
            name='taille',
            field=models.CharField(blank=True, choices=[('', 'Sans taille'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], help_text="Laisser vide si l'article n'a pas de taille (ex: jouet)", max_length=10),
        ),
        migrations.AlterField(
            model_name='produit',
            name='attribut',
            field=models.CharField(blank=True, help_text='Ex: Matière, marque, particularité...', max_length=255),
        ),
    ]
