# Generated by Django 5.2.16 on 2026-09-29 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0009_supprimer_champs_inutilises'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageprod',
            name='couleur',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
