# Generated by Django 6.1.1 on 2026-10-06 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0010_imageprod_couleur'),
        ('users', '0002_alter_administrateur_options_alter_client_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetraitStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(help_text="Nombre d'unités retirées du stock")),
                ('motif', models.CharField(choices=[('dommage', 'Produit endommagé'), ('perte', 'Perte ou vol'), ('peremption', 'Péremption'), ('autre', 'Autre motif')], max_length=20)),
                ('note', models.TextField(blank=True, help_text='Précisions (optionnel)')),
                ('cout_unitaire', models.FloatField(default=0, help_text="Prix d'achat unitaire au moment du retrait")),
                ('date_retrait', models.DateTimeField(auto_now_add=True)),
                ('commercant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retraits_stock', to='users.commercant')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retraits', to='produits.produit')),
            ],
            options={
                'verbose_name': 'Retrait de stock',
                'verbose_name_plural': 'Retraits de stock',
                'ordering': ['-date_retrait'],
            },
        ),
    ]
