# Generated by Django 5.2.16 on 2026-10-09 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_client_region_commune'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='commune',
        ),
        migrations.RemoveField(
            model_name='client',
            name='region',
        ),
    ]
