# Generated by Django 5.2.16 on 2026-10-09 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0009_commande_mode_paiement'),
        ('users', '0004_remove_client_commune_remove_client_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='commune',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='client',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='commandes.region'),
        ),
    ]
