# Generated by Django 5.2.16 on 2026-07-16 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0002_initial'),
        ('produits', '0002_alter_categorie_options_alter_depense_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commande',
            options={'ordering': ['-date_commande'], 'verbose_name': 'Commande', 'verbose_name_plural': 'Commandes'},
        ),
        migrations.AlterModelOptions(
            name='detailscommande',
            options={'verbose_name': 'Détail Commande', 'verbose_name_plural': 'Détails Commande'},
        ),
        migrations.AlterModelOptions(
            name='lignepanier',
            options={'verbose_name': 'Ligne Panier', 'verbose_name_plural': 'Lignes Panier'},
        ),
        migrations.AddField(
            model_name='panier',
            name='date_modification',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='detailscommande',
            name='produit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='details_commandes', to='produits.produit'),
        ),
    ]
