# Generated by Django 5.2.16 on 2026-07-26 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avis', '0005_alter_avis_options_remove_avis_details_commande_and_more'),
        ('commandes', '0003_alter_commande_options_alter_detailscommande_options_and_more'),
        ('produits', '0002_alter_categorie_options_alter_depense_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commande',
            options={'ordering': ['-date_commande'], 'verbose_name': 'Commande'},
        ),
        migrations.RenameField(
            model_name='lignepanier',
            old_name='prix_unitaire_snapshot',
            new_name='prix_unitaire_vente',
        ),
        migrations.AddField(
            model_name='lignepanier',
            name='commande',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes', to='commandes.commande'),
        ),
        migrations.AddField(
            model_name='lignepanier',
            name='offre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='produits.offreproduit'),
        ),
        migrations.AlterField(
            model_name='lignepanier',
            name='produit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='produits.produit'),
        ),
        migrations.DeleteModel(
            name='DetailsCommande',
        ),
    ]
