# Generated by Django 6.1.1 on 2026-09-18 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0007_remove_lignepanier_offre'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignepanier',
            name='couleur_choisie',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='lignepanier',
            name='taille_choisie',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
