# Generated by Django 5.2.16 on 2026-09-30 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0008_lignepanier_couleur_choisie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='mode_paiement',
            field=models.CharField(choices=[('wave', 'Wave'), ('orange_money', 'Orange Money'), ('carte', 'Carte bancaire')], default='wave', max_length=20),
        ),
    ]
