# Generated by Django 5.2.16 on 2026-08-27 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationClimatique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Ex : Hivernage, Saison sèche', max_length=100, unique=True)),
                ('code', models.SlugField(help_text='Identifiant technique (sans espace), ex : hivernage', unique=True)),
                ('mois_debut', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)])),
                ('jour_debut', models.PositiveSmallIntegerField(default=1)),
                ('mois_fin', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)])),
                ('jour_fin', models.PositiveSmallIntegerField(default=1)),
                ('conseil', models.TextField(help_text='Conseil affiché au commerçant durant cette saison')),
                ('icone', models.CharField(default='bi-cloud-sun', help_text='Classe Bootstrap Icons, ex : bi-cloud-rain-heavy, bi-sun', max_length=50)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Configuration climatique',
                'verbose_name_plural': 'Configurations climatiques',
                'ordering': ['mois_debut', 'jour_debut'],
            },
        ),
    ]
