# Generated by Django 5.2.16 on 2026-09-08 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sad', '0003_scinder_saison_seche'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configurationclimatique',
            options={'ordering': ['code'], 'verbose_name': 'Configuration climatique', 'verbose_name_plural': 'Configurations climatiques'},
        ),
        migrations.RemoveField(
            model_name='configurationclimatique',
            name='jour_debut',
        ),
        migrations.RemoveField(
            model_name='configurationclimatique',
            name='jour_fin',
        ),
        migrations.RemoveField(
            model_name='configurationclimatique',
            name='mois_debut',
        ),
        migrations.RemoveField(
            model_name='configurationclimatique',
            name='mois_fin',
        ),
        migrations.AlterField(
            model_name='configurationclimatique',
            name='code',
            field=models.CharField(choices=[('hivernage', 'Hivernage'), ('saison_seche_fraiche', 'Saison sèche fraîche (harmattan)'), ('saison_seche_chaude', 'Saison sèche chaude')], help_text="Saison à laquelle ce texte correspond (détectée via l'API météo).", max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='configurationclimatique',
            name='nom',
            field=models.CharField(help_text='Ex : Hivernage, Saison sèche fraîche', max_length=100),
        ),
    ]
