# Generated by Django 6.0.7 on 2026-07-15 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('avis', '0001_initial'),
        ('commandes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='avis',
            name='details_commande',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avis', to='commandes.detailscommande'),
        ),
    ]
