# Generated by Django 6.0.7 on 2026-07-15 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('avis', '0002_initial'),
        ('produits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='avis',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis_set', to='produits.produit'),
        ),
        migrations.AlterUniqueTogether(
            name='avis',
            unique_together={('client', 'produit')},
        ),
    ]
