# Generated by Django 5.2.16 on 2026-07-16 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avis', '0003_initial'),
        ('commandes', '0003_alter_commande_options_alter_detailscommande_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avis',
            options={'verbose_name': 'Avis', 'verbose_name_plural': 'Avis'},
        ),
        migrations.AlterField(
            model_name='avis',
            name='details_commande',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avis', to='commandes.detailscommande'),
        ),
        migrations.AlterField(
            model_name='avis',
            name='note',
            field=models.IntegerField(choices=[(1, '1 étoile'), (2, '2 étoiles'), (3, '3 étoiles'), (4, '4 étoiles'), (5, '5 étoiles')]),
        ),
        migrations.AlterField(
            model_name='avis',
            name='verifie_achat',
            field=models.BooleanField(default=False, help_text='True si le client a bien acheté ce produit'),
        ),
    ]
