# Generated by Django 5.2.16 on 2026-07-26 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avis', '0004_alter_avis_options_alter_avis_details_commande_and_more'),
        ('commandes', '0003_alter_commande_options_alter_detailscommande_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avis',
            options={'verbose_name': 'Avis'},
        ),
        migrations.RemoveField(
            model_name='avis',
            name='details_commande',
        ),
        migrations.AddField(
            model_name='avis',
            name='ligne_commande',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avis', to='commandes.lignepanier'),
        ),
        migrations.AlterField(
            model_name='avis',
            name='verifie_achat',
            field=models.BooleanField(default=False),
        ),
    ]
