# Generated by Django 6.0.7 on 2026-07-15 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EvenementSAD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_evenement', models.CharField(max_length=150)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('conseil_affiche', models.TextField(help_text='Conseil affiché au commerçant avant cet événement')),
            ],
            options={
                'verbose_name': 'Événement SAD',
                'ordering': ['date_debut'],
            },
        ),
    ]
