# Generated by Django 5.2.16 on 2026-07-16 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evenements', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evenementsad',
            options={'ordering': ['date_debut'], 'verbose_name': 'Événement SAD', 'verbose_name_plural': 'Événements SAD'},
        ),
    ]
