# Generated by Django 6.0.7 on 2026-07-15 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('type', models.CharField(choices=[('stock_bas', 'Stock bas'), ('stock_dormant', 'Stock dormant'), ('evenement', 'Événement'), ('commande', 'Nouvelle commande'), ('saison', 'Alerte saison')], max_length=20)),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('lu', models.BooleanField(default=False)),
                ('commercant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='users.commercant')),
            ],
            options={
                'verbose_name': 'Notification',
                'ordering': ['-date_envoi'],
            },
        ),
    ]
