# Generated by Django 5.2.16 on 2026-07-16 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-date_envoi'], 'verbose_name': 'Notification', 'verbose_name_plural': 'Notifications'},
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('stock_bas', '🔴 Stock bas'), ('stock_dormant', '🟡 Stock dormant'), ('evenement', '📅 Événement'), ('commande', '🛒 Nouvelle commande'), ('saison', '🌧️ Alerte saison')], max_length=20),
        ),
    ]
